add data from Get to Test
PowerShell/DSC pull request #244
Opened 2023-10-24 18:46 UTC by mgreenegit

2023-10-24 18:47 UTC, mgreenegit commented
Intended to address https://github.com/PowerShell/DSC/issues/160

2023-10-31 21:11 UTC, anmenaga requested changes
Needs some updates.

2023-10-31 21:11 UTC, anmenaga commented on powershellgroup/powershellgroup.resource.ps1
> +            $ResourceTypeName = ($r.type -split "/")[1]
If I'm reading this right, here (around line 302) `$r` is not defined.
Looks like you wanted to use `$inputobj_pscustomobj` instead of `$r`.

2023-10-31 21:11 UTC, anmenaga commented on powershellgroup/powershellgroup.resource.ps1
> +            $r.properties.psobject.properties | %{ $inputht[$_.Name] = $_.Value }
The input object has field `type` injected into it by `dsc`. This field has to be filtered out before passing the object down to `Invoke-DscResource` calls.

2023-11-08 15:02 UTC, mgreenegit commented
@anmenaga I closed the other PR and moved everything here. sorry for so many changes in one review.

2024-03-26 16:11 UTC, closed without merging