(DOCS) Updates for `preview.9`
PowerShell/DSC pull request #523
Opened 2024-08-16 19:16 UTC by michaeltlombardi

# PR Summary

These changes update the documentation and schemas for `preview.9`

## PR Context

Changes:

- [x] Changelog
- [ ] Schema definition updates
- [ ] Composed schema updates
- [ ] Reference documentation updates

2024-08-20 20:31 UTC, anmenaga approved these changes
LGTM with 1 typo fix.

2024-08-20 20:31 UTC, anmenaga commented on CHANGELOG.md
> +  caching version doesn't manage the property of the cache, the adapter rebuilds it with the new
```suggestion
  caching version doesn't match the property of the cache, the adapter rebuilds it with the new
```

2024-08-21 00:05 UTC, SteveL-MSFT reviewed
looks like more changes coming

2024-08-22 20:33 UTC, SteveL-MSFT requested changes

2024-08-22 20:33 UTC, SteveL-MSFT commented on docs/reference/schemas/config/functions/overview.md
> +To access a specific item in an array output, follow the closing paren of the function with an opening square bracket (`[`), then the integer index of the item you want to access, and then a closing
Is it common to use `paren` as shorthand for parenthesis?

2024-08-22 20:33 UTC, SteveL-MSFT commented on docs/reference/schemas/config/functions/overview.md
> +```yaml$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
```suggestion
```yaml
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
```

2024-08-23 03:36 UTC, SteveL-MSFT commented on docs/reference/schemas/config/functions/overview.md
> +To access a specific item in an array output, follow the closing paren of the function with an
One more `paren` here

2024-08-23 17:07 UTC, SteveL-MSFT approved these changes

2024-08-23 17:07 UTC, merged