Set a non-zero exit code when a resource not found
PowerShell/DSC pull request #561
Opened 2024-09-26 21:11 UTC by anmenaga

# PR Summary

`dsc resource ...` commands were just printing a `Resource not found` error, but exit code was 0.
This PR changes exist code to `7` in such cases.

before change:
```
PS C:\DSCv3> dsc resource get -r dfg/sdfg                     
2024-09-26T21:07:27.371778Z ERROR Resource not found: dfg/sdfg
PS C:\DSCv3> $LASTEXITCODE
0
```

after change:
```
PS C:\DSCv3> dsc resource get -r dfg/sdfg                     
2024-09-26T21:08:16.539682Z ERROR Resource not found: dfg/sdfg
PS C:\DSCv3> $LASTEXITCODE
7
```

2024-09-26 21:23 UTC, tgauth reviewed
does this exit code need to be added to the *.dsc.resource.jsons as part of this PR?

2024-09-26 21:26 UTC, anmenaga commented
> does this exit code need to be added to the *.dsc.resource.jsons as part of this PR?

No. This error signals a problem in dsc.exe discovery itself.

2024-09-26 21:34 UTC, tgauth approved these changes

2024-09-27 00:12 UTC, SteveL-MSFT requested changes
When `dsc` itself is used as a resource this error can come up so it should be added to the `group`, `assertion`, `parallel` resource manifests

2024-09-27 18:40 UTC, anmenaga commented
Updated `group`, `assertion`, `parallel` resource manifests as suggested.

2024-09-27 21:58 UTC, SteveL-MSFT commented
@anmenaga you need to add the new version of `cc` to our CFS feed

2024-10-03 20:04 UTC, SteveL-MSFT approved these changes

2024-10-03 20:04 UTC, merged